name: Regular Update

on:
  schedule:
    - cron: "0 2-14/6 * * *" # 每天, 时区+8

jobs:
  update:
    if: ${{ github.ref }} == "main"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          
      - name: Configure Git
        run: |
          git config --global user.email "khodahossein61@gmail.com"
          git config --global user.name "Saviorhoss"
          git remote set-url origin https://github.com/Saviorhoss/V2py.git
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python
        run: python main.py

      - name: Git Commit Push Action
        uses: Saviorhoss/git-commit-push@v1.3
